### ISSUE TITLE
Stripes Target Widget Texture Invisible Until Target Loses Health

### ISSUE THREAD

**Issue by UEAdmiral** [Backupiseasy/ThreatPlates#515]
Under Widgets>Target, the Stripes style no longer shows on top of the healthbar like it used to before Cata Pre-patch. It is only visible in the background of the nameplate after the target has started to lose HP. 

Probably a layering error?

**Comment by QuinncyJones** [comment]
To me it looks like the stripes are rendered on the background texture and not the life bar texture. I therefore use version 11.1.44 which does not have this problem.

**Comment by Backupiseasy** [comment]
You are right. That was a side-effect of the implementation to support soft-targeting. Still, the buggy part in the code - which I removed now - I have no idea anymore why it was there. I might have introduced (or re-introduced) an old bug again, maybe ...

 It's fixed now in the new version 11.2.3.

**Comment by QuinncyJones** [comment]
Thanks for the quick fix, but unfortunately the bug is back in version 11.2.4.

**Comment by Backupiseasy** [comment]
I cannot reproduce this currently. As you can see, the stripes highlight is shown just right for me:
![image](https://github.com/Backupiseasy/ThreatPlates/assets/20885351/ba388da5-ca9d-4426-ad44-0b414cb4a19f)
Not sure what is happening for you and what kind of setting could cause thisl.

**Comment by QuinncyJones** [comment]
Yes, it works with the latest version (11.2.4) No idea what that was. Thank you!

**Comment by Backupiseasy** [comment]
You're welcome. I still tweaked the layering a bit (between focus and target) (not in 11.2.4, but for the next version), so hopefully I do not introduce this issue again :)

**Comment by Backupiseasy** [comment]
If you experience it again, just comment here. Maybe it's a side-effect of some other bug and does not happen all the time, but only in certain situations.

**Comment by Backupiseasy** [comment]
Ok, now I found at least one situation where this happens. When switch from a profile without the stripes texture to a profile with the stripes texture while not target is selected. After that, the stripe texture does not show until you reload the UI.  It might be an update issue with the options, but I am not yet sure.

**Comment by QuinncyJones** [comment]
The problem occurred for me after updating from version 11.2.3 to version 11.2.4 and a subsequent reload. But I couldn't reproduce this. Anyway, thank you for an addon that does exactly what I need!

**Comment by Backupiseasy** [comment]
There definitely is an issue, e.g., when switching profiles. So I will look into that some more and update the post here with what I find out.
